// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20250108222745_fixed-info")]
    partial class fixedinfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("API.Entities.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuyerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("API.Entities.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("API.Entities.OrderAggregate.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuyerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DeliveryFee")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Subtotal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("API.Entities.OrderAggregate.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoImages")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("literalDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Leon's Cleaning",
                            DemoImages = "[\"https://blobstorage1114.blob.core.windows.net/images/product-1-1.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-1-2.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-1-3.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-1-4.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-1-5.webp\"]",
                            Description = "<div class='product-description'>\r\n  <h2>Biodegradable Dish Soap - Gentle on Hands</h2>\r\n  <p>\r\n    Keep your dishes sparkling clean while caring for the environment with our \r\n    <strong>Biodegradable Dish Soap</strong>. Made from \r\n    <em>natural ingredients</em>, this soap is tough on grease but gentle on your hands.\r\n  </p>\r\n  <ul>\r\n    <li><strong>Eco-Friendly:</strong> Completely biodegradable, reducing environmental impact.</li>\r\n    <li><strong>Natural Formula:</strong> Made with plant-based ingredients for a safer clean.</li>\r\n    <li><strong>Gentle on Skin:</strong> Perfect for sensitive hands with no harsh chemicals.</li>\r\n    <li><strong>Powerful Cleaning:</strong> Effectively cuts through grease and grime.</li>\r\n  </ul>\r\n  <p>\r\n    Choose a product that combines <strong>sustainability</strong> and <strong>effectiveness</strong>. \r\n    Make dishwashing a cleaner, greener experience today!\r\n  </p>\r\n</div>",
                            Name = "Biodegradable dish.",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product1.jpg",
                            Price = 13.99,
                            QuantityInStock = 13,
                            Type = "Bath",
                            literalDescription = "Biodegradable dish soap made from natural ingredients, gentle on hands."
                        },
                        new
                        {
                            Id = 2,
                            Brand = "eSayClean",
                            DemoImages = "[\"https://blobstorage1114.blob.core.windows.net/images/product-2-1.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-2-2.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-2-3.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-2-4.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-2-5.webp\"]",
                            Description = "<div class='product-description'>\r\n  <h2>Non-Toxic, Plant-Based Laundry Detergent for Sensitive Skin</h2>\r\n  <p>\r\n    Experience a gentle yet effective clean with our \r\n    <strong>Non-Toxic, Plant-Based Laundry Detergent</strong>. Specially formulated for those with \r\n    <em>sensitive skin</em>, this detergent is free from harsh chemicals and powered by natural ingredients.\r\n  </p>\r\n  <ul>\r\n    <li><strong>Gentle on Skin:</strong> Perfect for individuals with allergies or sensitivities.</li>\r\n    <li><strong>Plant-Based Formula:</strong> Made with eco-friendly, biodegradable ingredients.</li>\r\n    <li><strong>Non-Toxic:</strong> Free from harmful chemicals, ensuring a safe and clean wash.</li>\r\n    <li><strong>Fresh Clean:</strong> Effectively removes stains and odors while leaving your clothes soft.</li>\r\n  </ul>\r\n  <p>\r\n    Make the switch to a detergent that’s as kind to your skin as it is to the planet. \r\n    Try our plant-powered solution today and embrace a healthier, more sustainable way to do laundry.\r\n  </p>\r\n</div>",
                            Name = "Non-toxic, plant-based laundry detergent for sensitive skin",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product2.jpg",
                            Price = 29.989999999999998,
                            QuantityInStock = 12,
                            Type = "Bath",
                            literalDescription = "Make the switch to a detergent that’s as kind to your skin as it is to the planet. Try our plant-powered solution today and embrace a healthier, more sustainable way to do laundry."
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Timerland",
                            DemoImages = "[\"https://blobstorage1114.blob.core.windows.net/images/product-3-1.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-3-2.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-3-3.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-3-4.webp\"]",
                            Description = "<div class='product-description'>\r\n  <h2>Microfiber Cleaning Cloths - Reusable and Effective</h2>\r\n  <p>\r\n    Say goodbye to dirt and streaks with our premium \r\n    <strong>Microfiber Cleaning Cloths</strong>. Designed to be \r\n    <em>gentle yet powerful</em>, these cloths are perfect for cleaning \r\n    <strong>all types of surfaces</strong>, from glass to wood and everything in between.\r\n  </p>\r\n  <ul>\r\n    <li><strong>Reusable and Durable:</strong> Built to last, these cloths can be washed and reused, reducing waste.</li>\r\n    <li><strong>Effective on All Surfaces:</strong> Safely cleans glass, mirrors, countertops, stainless steel, and more.</li>\r\n    <li><strong>Lint-Free and Scratch-Free:</strong> Leaves surfaces spotless without causing damage.</li>\r\n    <li><strong>Eco-Friendly Choice:</strong> A sustainable alternative to disposable cleaning supplies.</li>\r\n  </ul>\r\n  <p>\r\n    Upgrade your cleaning routine with these versatile and environmentally-friendly \r\n    <strong>microfiber cloths</strong>. Perfect for homes, offices, and cars, they are \r\n    the ultimate cleaning companion.\r\n  </p>\r\n</div>",
                            Name = "Microfiber cleaning cloths, reusable and effective on all surfaces.",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product3.webp",
                            Price = 18.989999999999998,
                            QuantityInStock = 18,
                            Type = "Cloths",
                            literalDescription = "Say goodbye to dirt and streaks with our premium Microfiber Cleaning Cloths. Designed to be gentle yet powerful, these cloths are perfect for cleaning all types of surfaces, from glass to wood and everything in between."
                        },
                        new
                        {
                            Id = 4,
                            Brand = "eSayClean",
                            DemoImages = "[\"https://blobstorage1114.blob.core.windows.net/images/product-4-1.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-4-2.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-4-3.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-4-4.webp\"]",
                            Description = "<div class='product-description'>\r\n  <h2>Microfiber Cleaning Cloths - Reusable and Effective</h2>\r\n  <p>\r\n    Say goodbye to dirt and streaks with our premium \r\n    <strong>Microfiber Cleaning Cloths</strong>. Designed to be \r\n    <em>gentle yet powerful</em>, these cloths are perfect for cleaning \r\n    <strong>all types of surfaces</strong>, from glass to wood and everything in between.\r\n  </p>\r\n  <ul>\r\n    <li><strong>Reusable and Durable:</strong> Built to last, these cloths can be washed and reused, reducing waste.</li>\r\n    <li><strong>Effective on All Surfaces:</strong> Safely cleans glass, mirrors, countertops, stainless steel, and more.</li>\r\n    <li><strong>Lint-Free and Scratch-Free:</strong> Leaves surfaces spotless without causing damage.</li>\r\n    <li><strong>Eco-Friendly Choice:</strong> A sustainable alternative to disposable cleaning supplies.</li>\r\n  </ul>\r\n  <p>\r\n    Upgrade your cleaning routine with these versatile and environmentally-friendly \r\n    <strong>microfiber cloths</strong>. Perfect for homes, offices, and cars, they are \r\n    the ultimate cleaning companion.\r\n  </p>\r\n</div>",
                            Name = "Concentrated all-purpose cleaner, eco-friendly and powerful against grime.",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product4.webp",
                            Price = 14.99,
                            QuantityInStock = 19,
                            Type = "Cleaner",
                            literalDescription = "Say goodbye to dirt and streaks with our premium Microfiber Cleaning Cloths. Designed to be gentle yet powerful, these cloths are perfect for cleaning all types of surfaces, from glass to wood and everything in between."
                        },
                        new
                        {
                            Id = 5,
                            Brand = "eSayClean",
                            DemoImages = "[\"https://blobstorage1114.blob.core.windows.net/images/product-5-1.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-5-2.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-5-3.webp\"]",
                            Description = "<div class='product-description'>\r\n  <h2>Natural and Sustainable Beauty Essentials</h2>\r\n  <p>\r\n    Transform your self-care routine with this thoughtfully curated set of \r\n    <strong>eco-friendly beauty essentials</strong>. Combining functionality \r\n    and sustainability, this collection is perfect for a mindful, \r\n    environmentally conscious lifestyle.\r\n  </p>\r\n  <ul>\r\n    <li><strong>Natural Wooden Body Brush:</strong> Features soft, natural bristles for gentle exfoliation and improved circulation.</li>\r\n    <li><strong>Powdered Skincare:</strong> A jar of gentle exfoliating powder to refresh and rejuvenate your skin.</li>\r\n    <li><strong>Reusable Cotton Pads:</strong> Soft and durable, ideal for makeup removal and reducing waste.</li>\r\n    <li><strong>Handcrafted Soap Bar:</strong> Made with natural ingredients, perfect for a luxurious cleanse.</li>\r\n    <li><strong>Textured Fabric Pouch:</strong> A stylish and practical addition for storing your beauty essentials.</li>\r\n  </ul>\r\n  <p>\r\n    Embrace a <strong>minimalistic aesthetic</strong> while caring for the planet. \r\n    This set is designed to elevate your skincare experience, bringing together \r\n    beauty, sustainability, and simplicity in one luxurious package.\r\n  </p>\r\n</div>",
                            Name = "Natural wood polish restores shine without harmful chemicals",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product5.webp",
                            Price = 15.0,
                            QuantityInStock = 14,
                            Type = "Bath",
                            literalDescription = "Natural wood polish restores shine without harmful chemicals.Combining functionality and sustainability, this collection is perfect for a mindful, environmentally conscious lifestyle"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "eSayClean",
                            DemoImages = "[\"https://blobstorage1114.blob.core.windows.net/images/product-6-1.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-6-2.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-6-3.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-6-3.webp\"]",
                            Description = "<div class='product-description'>\r\n  <h1>Whimsical Cat-Themed Ceramic Tea Set</h1>\r\n  <p>\r\n    Add a touch of charm to your tea time with this delightful <strong>cat-themed ceramic tea set</strong>. Featuring playful cat illustrations with vibrant umbrellas, this set is both functional and a beautiful piece of art. Perfect for cat lovers and tea enthusiasts alike!\r\n  </p>\r\n  <p><strong>What's Included:</strong></p>\r\n  <ul>\r\n    <li>1 Teapot with a sturdy handle and whimsical design</li>\r\n    <li>Matching teacups with playful cat and umbrella illustrations</li>\r\n    <li>Beautifully crafted saucers to complete the set</li>\r\n  </ul>\r\n  <p><strong>Key Features:</strong></p>\r\n  <ul>\r\n    <li><strong>High-Quality Ceramic:</strong> Durable, heat-resistant material for long-lasting use.</li>\r\n    <li><strong>Adorable Design:</strong> Colorful and playful cat illustrations with umbrella accents.</li>\r\n    <li><strong>Perfect for Any Occasion:</strong> Ideal for tea parties, casual use, or as a unique gift.</li>\r\n    <li><strong>Easy to Clean:</strong> Smooth surface makes cleaning a breeze.</li>\r\n  </ul>\r\n  <p><strong>Specifications:</strong></p>\r\n  <ul>\r\n    <li>Material: High-quality ceramic</li>\r\n    <li>Teapot Capacity: 1.2 liters</li>\r\n    <li>Number of Cups: 6 matching teacups</li>\r\n    <li>Design: Playful cats with colorful umbrellas</li>\r\n  </ul>\r\n  <p>\r\n    This tea set combines practicality with a whimsical design that will delight anyone who sees it. Whether you're hosting guests or enjoying a quiet tea moment, this set will bring joy and style to your experience.\r\n  </p>\r\n  <p><strong>Customer Reviews:</strong></p>\r\n  <p>\r\n    ★★★★★ (4.8/5) - 'Such a cute tea set! The cat designs are adorable, and the quality is excellent.'\r\n  </p>\r\n</div>",
                            Name = "Teapot with a sturdy handle and whimsical design",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product6.webp",
                            Price = 30.989999999999998,
                            QuantityInStock = 12,
                            Type = "Cleaner",
                            literalDescription = "Combining effective antibacterial action with the nourishing benefits of aloe vera, this hand sanitizer is a must-have for maintaining hygiene without compromising on skin care. Ideal for everyday use and suitable for all skin types."
                        },
                        new
                        {
                            Id = 7,
                            Brand = "eSayClean",
                            DemoImages = "[\"https://blobstorage1114.blob.core.windows.net/images/product-7-1.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-7-2.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-7-3.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-7-4.webp\",\"https://blobstorage1114.blob.core.windows.net/images/product-7-5.webp\"]",
                            Description = "<div class='product-description'>\r\n  <h1>Antibacterial Hand Sanitizer with Moisturizing Aloe Vera Gel</h1>\r\n  <p>\r\n    Keep your hands clean and germ-free with our <strong>antibacterial hand sanitizer</strong>. Infused with <em>moisturizing aloe vera gel</em>, it provides effective protection while keeping your skin soft and hydrated.\r\n  </p>\r\n  <p><strong>Key Features:</strong></p>\r\n  <ul>\r\n    <li><strong>Powerful Germ Protection:</strong> Eliminates 99.9% of bacteria and viruses.</li>\r\n    <li><strong>Moisturizing Formula:</strong> Enriched with aloe vera to prevent dryness and irritation.</li>\r\n    <li><strong>Quick Absorption:</strong> Non-sticky, fast-drying formula for hassle-free use.</li>\r\n    <li><strong>Portable and Convenient:</strong> Ideal for use at home, work, or on the go.</li>\r\n  </ul>\r\n  <p>\r\n    This hand sanitizer combines superior germ-fighting power with the soothing benefits of aloe vera, making it perfect for daily use. It's an essential addition to your hygiene routine, ensuring cleanliness without compromising on skin care.\r\n  </p>\r\n  <p><strong>Customer Reviews:</strong></p>\r\n  <p>\r\n    ★★★★☆ (4.5/5) - 'Keeps my hands feeling fresh and moisturized. Love the aloe vera scent!'\r\n  </p>\r\n</div>",
                            Name = "Antibacterial hand sanitizer",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product7.webp",
                            Price = 41.0,
                            QuantityInStock = 21,
                            Type = "Cleaner",
                            literalDescription = "This hand sanitizer combines superior germ-fighting power with the soothing benefits of aloe vera, making it perfect for daily use. It's an essential addition to your hygiene routine, ensuring cleanliness without compromising on skin care."
                        },
                        new
                        {
                            Id = 8,
                            Brand = "eSayClean",
                            Description = "<div class='product-description'>\r\n  <h1>Oxygen Bleach Alternative - Safe for Colors and the Environment</h1>\r\n  <p>\r\n    Discover a powerful and eco-friendly solution for your laundry needs with our <strong>oxygen bleach alternative</strong>. This versatile product is designed to brighten whites, clean tough stains, and maintain the vibrancy of your colored fabrics, all while being gentle on the environment.\r\n  </p>\r\n  <p><strong>Key Features:</strong></p>\r\n  <ul>\r\n    <li><strong>Safe for Colors:</strong> Protects the vibrancy of colored fabrics while effectively removing stains.</li>\r\n    <li><strong>Environmentally Friendly:</strong> Biodegradable formula that is safe for the planet.</li>\r\n    <li><strong>Versatile Use:</strong> Ideal for laundry, cleaning surfaces, and more.</li>\r\n    <li><strong>Non-Toxic:</strong> Free from harsh chemicals and chlorine.</li>\r\n  </ul>\r\n  <p>\r\n    This oxygen bleach alternative is perfect for those who want a cleaner, greener home. It offers powerful cleaning without the use of harsh chemicals, making it a safe choice for your family and the environment.\r\n  </p>\r\n  <p><strong>Customer Reviews:</strong></p>\r\n  <p>\r\n    ★★★★★ (4.7/5) - 'Works wonderfully on my laundry and is safe for all my colored clothes. Highly recommend!'\r\n  </p>\r\n</div>",
                            Name = "Green eSayClean Woolen bleach",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product8.webp",
                            Price = 23.0,
                            QuantityInStock = 32,
                            Type = "Cleaner",
                            literalDescription = "Oxygen bleach alternative, safe for colors and the environment."
                        },
                        new
                        {
                            Id = 9,
                            Brand = "eSayClean",
                            Description = "<div class='product-description'>\r\n  <h1>Oxygen Bleach Alternative - Safe for Colors and the Environment</h1>\r\n  <p>\r\n    Discover a powerful and eco-friendly solution for your laundry needs with our <strong>oxygen bleach alternative</strong>. This versatile product is designed to brighten whites, clean tough stains, and maintain the vibrancy of your colored fabrics, all while being gentle on the environment.\r\n  </p>\r\n  <p><strong>Key Features:</strong></p>\r\n  <ul>\r\n    <li><strong>Safe for Colors:</strong> Protects the vibrancy of colored fabrics while effectively removing stains.</li>\r\n    <li><strong>Environmentally Friendly:</strong> Biodegradable formula that is safe for the planet.</li>\r\n    <li><strong>Versatile Use:</strong> Ideal for laundry, cleaning surfaces, and more.</li>\r\n    <li><strong>Non-Toxic:</strong> Free from harsh chemicals and chlorine.</li>\r\n  </ul>\r\n  <p>\r\n    This oxygen bleach alternative is perfect for those who want a cleaner, greener home. It offers powerful cleaning without the use of harsh chemicals, making it a safe choice for your family and the environment.\r\n  </p>\r\n  <p><strong>Customer Reviews:</strong></p>\r\n  <p>\r\n    ★★★★★ (4.7/5) - 'Works wonderfully on my laundry and is safe for all my colored clothes. Highly recommend!'\r\n  </p>\r\n</div>",
                            Name = "Citrus degreaser",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product9.webp",
                            Price = 13.0,
                            QuantityInStock = 10,
                            Type = "Cloths",
                            literalDescription = "Citrus degreaser cuts through tough grease without harsh fumes."
                        },
                        new
                        {
                            Id = 10,
                            Brand = "eSayClean",
                            DemoImages = "[\"https://blobstorage1114.blob.core.windows.net/images/1.webp\",\"https://blobstorage1114.blob.core.windows.net/images/2.webp\",\"https://blobstorage1114.blob.core.windows.net/images/3.webp\",\"https://blobstorage1114.blob.core.windows.net/images/4.webp\",\"https://blobstorage1114.blob.core.windows.net/images/5.webp\"]",
                            Description = "<p>\r\n                Elevate your bathroom or spa experience with our\r\n                <strong>luxuriously soft white rolled towels</strong>. Made from\r\n                premium-quality cotton, these towels are ultra-absorbent,\r\n                durable, and gentle on the skin, making them perfect for\r\n                everyday use or special occasions. Each towel is elegantly\r\n                rolled and displayed on a stylish macrame swing, showcasing a\r\n                clean, minimalist aesthetic that blends effortlessly into any\r\n                décor. Whether you're upgrading your bathroom essentials or\r\n                looking for a thoughtful gift, these towels combine practicality\r\n                with timeless sophistication.\r\n              </p>\r\n              <ul className='list-disc list-inside'>\r\n                <li>\r\n                  <strong>Material</strong>: 100% Premium Cotton\r\n                </li>\r\n                <li>\r\n                  <strong>Features</strong>: Highly absorbent, quick-drying, and\r\n                  soft to the touch\r\n                </li>\r\n                <li>\r\n                  <strong>Ideal For</strong>: Bathrooms, spas, or as decorative\r\n                  accents\r\n                </li>\r\n                <li>\r\n                  <strong>Care Instructions</strong>: Machine washable, tumble\r\n                  dry on low\r\n                </li>\r\n              </ul>\r\n              <p>\r\n                Bring a touch of elegance and comfort to your home with these\r\n                versatile and beautifully designed towels.\r\n              </p>",
                            Name = "Glass cleaner leaves streak-free shine, no residue left behind",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product10.webp",
                            Price = 19.989999999999998,
                            QuantityInStock = 10,
                            Type = "Cloths",
                            literalDescription = "Discover a powerful and eco-friendly solution for your laundry needs with our <strong>oxygen bleach alternative</strong>. This versatile product is designed to brighten whites, clean tough stains, and maintain the vibrancy of your colored fabrics, all while being gentle on the environment."
                        },
                        new
                        {
                            Id = 11,
                            Brand = "eSayClean",
                            Description = "<div class='product-description'>\r\n  <h1>Oxygen Bleach Alternative - Safe for Colors and the Environment</h1>\r\n  <p>\r\n    Discover a powerful and eco-friendly solution for your laundry needs with our <strong>oxygen bleach alternative</strong>. This versatile product is designed to brighten whites, clean tough stains, and maintain the vibrancy of your colored fabrics, all while being gentle on the environment.\r\n  </p>\r\n  <p><strong>Key Features:</strong></p>\r\n  <ul>\r\n    <li><strong>Safe for Colors:</strong> Protects the vibrancy of colored fabrics while effectively removing stains.</li>\r\n    <li><strong>Environmentally Friendly:</strong> Biodegradable formula that is safe for the planet.</li>\r\n    <li><strong>Versatile Use:</strong> Ideal for laundry, cleaning surfaces, and more.</li>\r\n    <li><strong>Non-Toxic:</strong> Free from harsh chemicals and chlorine.</li>\r\n  </ul>\r\n  <p>\r\n    This oxygen bleach alternative is perfect for those who want a cleaner, greener home. It offers powerful cleaning without the use of harsh chemicals, making it a safe choice for your family and the environment.\r\n  </p>\r\n  <p><strong>Customer Reviews:</strong></p>\r\n  <p>\r\n    ★★★★★ (4.7/5) - 'Works wonderfully on my laundry and is safe for all my colored clothes. Highly recommend!'\r\n  </p>\r\n</div>",
                            Name = "Green Code Cloths",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product11.webp",
                            Price = 15.99,
                            QuantityInStock = 100,
                            Type = "Cloths",
                            literalDescription = "Carpet shampooer with stain remover for deep cleaning carpets."
                        },
                        new
                        {
                            Id = 12,
                            Brand = "eSayClean",
                            Description = "<div class='product-description'>\r\n  <h1>Oxygen Bleach Alternative - Safe for Colors and the Environment</h1>\r\n  <p>\r\n    Discover a powerful and eco-friendly solution for your laundry needs with our <strong>oxygen bleach alternative</strong>. This versatile product is designed to brighten whites, clean tough stains, and maintain the vibrancy of your colored fabrics, all while being gentle on the environment.\r\n  </p>\r\n  <p><strong>Key Features:</strong></p>\r\n  <ul>\r\n    <li><strong>Safe for Colors:</strong> Protects the vibrancy of colored fabrics while effectively removing stains.</li>\r\n    <li><strong>Environmentally Friendly:</strong> Biodegradable formula that is safe for the planet.</li>\r\n    <li><strong>Versatile Use:</strong> Ideal for laundry, cleaning surfaces, and more.</li>\r\n    <li><strong>Non-Toxic:</strong> Free from harsh chemicals and chlorine.</li>\r\n  </ul>\r\n  <p>\r\n    This oxygen bleach alternative is perfect for those who want a cleaner, greener home. It offers powerful cleaning without the use of harsh chemicals, making it a safe choice for your family and the environment.\r\n  </p>\r\n  <p><strong>Customer Reviews:</strong></p>\r\n  <p>\r\n    ★★★★★ (4.7/5) - 'Works wonderfully on my laundry and is safe for all my colored clothes. Highly recommend!'\r\n  </p>\r\n</div>",
                            Name = "Enzyme-based drain cleaner",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product12.webp",
                            Price = 19.989999999999998,
                            QuantityInStock = 12,
                            Type = "Cloths",
                            literalDescription = "Enzyme-based drain cleaner safely breaks down organic matter."
                        },
                        new
                        {
                            Id = 13,
                            Brand = "eSayClean",
                            Description = "<div class='product-description'>\r\n  <h1>Oxygen Bleach Alternative - Safe for Colors and the Environment</h1>\r\n  <p>\r\n    Discover a powerful and eco-friendly solution for your laundry needs with our <strong>oxygen bleach alternative</strong>. This versatile product is designed to brighten whites, clean tough stains, and maintain the vibrancy of your colored fabrics, all while being gentle on the environment.\r\n  </p>\r\n  <p><strong>Key Features:</strong></p>\r\n  <ul>\r\n    <li><strong>Safe for Colors:</strong> Protects the vibrancy of colored fabrics while effectively removing stains.</li>\r\n    <li><strong>Environmentally Friendly:</strong> Biodegradable formula that is safe for the planet.</li>\r\n    <li><strong>Versatile Use:</strong> Ideal for laundry, cleaning surfaces, and more.</li>\r\n    <li><strong>Non-Toxic:</strong> Free from harsh chemicals and chlorine.</li>\r\n  </ul>\r\n  <p>\r\n    This oxygen bleach alternative is perfect for those who want a cleaner, greener home. It offers powerful cleaning without the use of harsh chemicals, making it a safe choice for your family and the environment.\r\n  </p>\r\n  <p><strong>Customer Reviews:</strong></p>\r\n  <p>\r\n    ★★★★★ (4.7/5) - 'Works wonderfully on my laundry and is safe for all my colored clothes. Highly recommend!'\r\n  </p>\r\n</div>",
                            Name = "Mineral-based toilet bowl cleaner",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product13.webp",
                            Price = 18.989999999999998,
                            QuantityInStock = 100,
                            Type = "Cleaner",
                            literalDescription = "Mineral-based toilet bowl cleaner, effective and environmentally friendly."
                        },
                        new
                        {
                            Id = 14,
                            Brand = "eSayClean",
                            Description = "<div class='product-description'>\r\n  <h1>Oxygen Bleach Alternative - Safe for Colors and the Environment</h1>\r\n  <p>\r\n    Discover a powerful and eco-friendly solution for your laundry needs with our <strong>oxygen bleach alternative</strong>. This versatile product is designed to brighten whites, clean tough stains, and maintain the vibrancy of your colored fabrics, all while being gentle on the environment.\r\n  </p>\r\n  <p><strong>Key Features:</strong></p>\r\n  <ul>\r\n    <li><strong>Safe for Colors:</strong> Protects the vibrancy of colored fabrics while effectively removing stains.</li>\r\n    <li><strong>Environmentally Friendly:</strong> Biodegradable formula that is safe for the planet.</li>\r\n    <li><strong>Versatile Use:</strong> Ideal for laundry, cleaning surfaces, and more.</li>\r\n    <li><strong>Non-Toxic:</strong> Free from harsh chemicals and chlorine.</li>\r\n  </ul>\r\n  <p>\r\n    This oxygen bleach alternative is perfect for those who want a cleaner, greener home. It offers powerful cleaning without the use of harsh chemicals, making it a safe choice for your family and the environment.\r\n  </p>\r\n  <p><strong>Customer Reviews:</strong></p>\r\n  <p>\r\n    ★★★★★ (4.7/5) - 'Works wonderfully on my laundry and is safe for all my colored clothes. Highly recommend!'\r\n  </p>\r\n</div>",
                            Name = "eSayClean Red Cloths",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product14.webp",
                            Price = 29.989999999999998,
                            QuantityInStock = 32,
                            Type = "Cloths",
                            literalDescription = "Odor eliminator uses activated charcoal to absorb bad smells."
                        },
                        new
                        {
                            Id = 15,
                            Brand = "eSayClean",
                            Description = "<div class='product-description'>\r\n  <h1>Oxygen Bleach Alternative - Safe for Colors and the Environment</h1>\r\n  <p>\r\n    Discover a powerful and eco-friendly solution for your laundry needs with our <strong>oxygen bleach alternative</strong>. This versatile product is designed to brighten whites, clean tough stains, and maintain the vibrancy of your colored fabrics, all while being gentle on the environment.\r\n  </p>\r\n  <p><strong>Key Features:</strong></p>\r\n  <ul>\r\n    <li><strong>Safe for Colors:</strong> Protects the vibrancy of colored fabrics while effectively removing stains.</li>\r\n    <li><strong>Environmentally Friendly:</strong> Biodegradable formula that is safe for the planet.</li>\r\n    <li><strong>Versatile Use:</strong> Ideal for laundry, cleaning surfaces, and more.</li>\r\n    <li><strong>Non-Toxic:</strong> Free from harsh chemicals and chlorine.</li>\r\n  </ul>\r\n  <p>\r\n    This oxygen bleach alternative is perfect for those who want a cleaner, greener home. It offers powerful cleaning without the use of harsh chemicals, making it a safe choice for your family and the environment.\r\n  </p>\r\n  <p><strong>Customer Reviews:</strong></p>\r\n  <p>\r\n    ★★★★★ (4.7/5) - 'Works wonderfully on my laundry and is safe for all my colored clothes. Highly recommend!'\r\n  </p>\r\n</div>",
                            Name = "Vinegar-free fabric softener",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product15.webp",
                            Price = 34.0,
                            QuantityInStock = 12,
                            Type = "Cleaner",
                            literalDescription = "Vinegar-free fabric softener, keeps clothes soft and fresh."
                        },
                        new
                        {
                            Id = 16,
                            Brand = "eSayClean",
                            Description = "<div class='product-description'>\r\n  <h1>Oxygen Bleach Alternative - Safe for Colors and the Environment</h1>\r\n  <p>\r\n    Discover a powerful and eco-friendly solution for your laundry needs with our <strong>oxygen bleach alternative</strong>. This versatile product is designed to brighten whites, clean tough stains, and maintain the vibrancy of your colored fabrics, all while being gentle on the environment.\r\n  </p>\r\n  <p><strong>Key Features:</strong></p>\r\n  <ul>\r\n    <li><strong>Safe for Colors:</strong> Protects the vibrancy of colored fabrics while effectively removing stains.</li>\r\n    <li><strong>Environmentally Friendly:</strong> Biodegradable formula that is safe for the planet.</li>\r\n    <li><strong>Versatile Use:</strong> Ideal for laundry, cleaning surfaces, and more.</li>\r\n    <li><strong>Non-Toxic:</strong> Free from harsh chemicals and chlorine.</li>\r\n  </ul>\r\n  <p>\r\n    This oxygen bleach alternative is perfect for those who want a cleaner, greener home. It offers powerful cleaning without the use of harsh chemicals, making it a safe choice for your family and the environment.\r\n  </p>\r\n  <p><strong>Customer Reviews:</strong></p>\r\n  <p>\r\n    ★★★★★ (4.7/5) - 'Works wonderfully on my laundry and is safe for all my colored clothes. Highly recommend!'\r\n  </p>\r\n</div>",
                            Name = "Car wash solution",
                            PictureUrl = "https://blobstorage1114.blob.core.windows.net/images/product16.webp",
                            Price = 43.0,
                            QuantityInStock = 100,
                            Type = "Bath",
                            literalDescription = "Eco-friendly car wash solution, biodegradable and non-toxic."
                        });
                });

            modelBuilder.Entity("API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("API.Entities.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserAddress");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("API.Entities.BasketItem", b =>
                {
                    b.HasOne("API.Entities.Basket", "Basket")
                        .WithMany("Items")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Entities.OrderAggregate.Order", b =>
                {
                    b.OwnsOne("API.Entities.OrderAggregate.ShippingAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Address1")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address2")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FullName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Zip")
                                .HasColumnType("TEXT");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("API.Entities.OrderAggregate.OrderItem", b =>
                {
                    b.HasOne("API.Entities.OrderAggregate.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.OwnsOne("API.Entities.OrderAggregate.ProductItemOrdered", "ItemOrdered", b1 =>
                        {
                            b1.Property<int>("OrderItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PictureUrl")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ProductId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItem");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("ItemOrdered");
                });

            modelBuilder.Entity("API.Entities.UserAddress", b =>
                {
                    b.HasOne("API.Entities.User", null)
                        .WithOne("Address")
                        .HasForeignKey("API.Entities.UserAddress", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("API.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("API.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("API.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("API.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("API.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Entities.Basket", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("API.Entities.OrderAggregate.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("API.Entities.User", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
